### PR TITLE
Add C-h as delete word hotkey

### LINKED ISSUE #50: ctrl+h to backspace
Can you add ctrl+h to backspace? I use ctrl+h to backspace on my terminal and in my terminal based editors. Thanks.

### PR DESCRIPTION
**Pull request by idevtier**
Closes #50

### CODE REVIEW

**Review by Samyak2 — CHANGES_REQUESTED** [review]
If I understand correctly, #50 asked for `ctrl-h` to be an alternative for backspace (this is how it seems to work in the shell as well) and not `ctrl-w` :)

Could you correct this?

**Comment by idevtier** [comment]
You offer to add option for choosing word delete hotkey? Like add some config file and set it's value there. In theory config file seems good, because it will be possible to add the feature to change any hotkey

**Comment by Samyak2** [comment]
No, I meant that `Key::Ctrl('h')` should behave like `Key::Backspace` and not `Key::Ctrl('w')`

**Review by Samyak2 — APPROVED** [review]
LGTM. Thank you for the contribution! :)

**Pull request merged**
